// Copyright 2025 Robin Liu <robinliu27@163.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/robinlg/onexblog. The professional
// version of this repository is https://github.com/robinlg/onexblog.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnexBlog_Healthz_FullMethodName = "/v1.OnexBlog/Healthz"
)

// OnexBlogClient is the client API for OnexBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OnexBlog 定义了一个 OnexBlog RPC 服务
type OnexBlogClient interface {
	// Healthz 健康检查
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type onexBlogClient struct {
	cc grpc.ClientConnInterface
}

func NewOnexBlogClient(cc grpc.ClientConnInterface) OnexBlogClient {
	return &onexBlogClient{cc}
}

func (c *onexBlogClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, OnexBlog_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnexBlogServer is the server API for OnexBlog service.
// All implementations must embed UnimplementedOnexBlogServer
// for forward compatibility.
//
// OnexBlog 定义了一个 OnexBlog RPC 服务
type OnexBlogServer interface {
	// Healthz 健康检查
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	mustEmbedUnimplementedOnexBlogServer()
}

// UnimplementedOnexBlogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnexBlogServer struct{}

func (UnimplementedOnexBlogServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedOnexBlogServer) mustEmbedUnimplementedOnexBlogServer() {}
func (UnimplementedOnexBlogServer) testEmbeddedByValue()                  {}

// UnsafeOnexBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnexBlogServer will
// result in compilation errors.
type UnsafeOnexBlogServer interface {
	mustEmbedUnimplementedOnexBlogServer()
}

func RegisterOnexBlogServer(s grpc.ServiceRegistrar, srv OnexBlogServer) {
	// If the following call pancis, it indicates UnimplementedOnexBlogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnexBlog_ServiceDesc, srv)
}

func _OnexBlog_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnexBlogServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnexBlog_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnexBlogServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OnexBlog_ServiceDesc is the grpc.ServiceDesc for OnexBlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnexBlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OnexBlog",
	HandlerType: (*OnexBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _OnexBlog_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/v1/apiserver.proto",
}
